# Generated by Django 6.0.6 on 2026-06-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advance',
            new_name='advances_ad_employe_d25ac6_idx',
            old_name='advances_ad_employe_d48509_idx',
        ),
    ]
