version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
