# Generated by Django 6.0.6 on 2026-06-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salary',
            new_name='salaries_sa_employe_b9ef6d_idx',
            old_name='salaries_sa_employe_f983b8_idx',
        ),
    ]
