# Generated by Django 6.0.6 on 2026-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_rename_salaries_sa_employe_f983b8_idx_salaries_sa_employe_b9ef6d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
