# Generated by Django 6.0.6 on 2026-06-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_e_first_n_597cbd_idx',
            old_name='employees_e_first__28f7b7_idx',
        ),
    ]
